apiVersion: v1
kind: ConfigMap
metadata:
  name: beu-cro-adv-daba-26-config
  namespace: beu-cro-adv-daba-26
data:
  TZ: "Europe/Zurich"
  NEO4J_IP: "neo4j"
  MAX_NODES: "1000" 
  JSON_FILE: "/data/dblpExample.json"
