apiVersion: v1
kind: ConfigMap
metadata:
  name: beu-cro-adv-daba-26-config
  namespace: beu-cro-adv-daba-26 # 📝 Remplacer par votre namespace
data:
  TZ: "Europe/Zurich"
  PGDATA: "/var/lib/postgresql/data/pgdata" # Chemin des données PostgreSQL
  SERVERPOD_RUN_MODE: "production"
  SERVERPOD_DATABASE_HOST: "postgres-service" # 📝 Nom exact du Service K8s de la DB (défini étape 5)
  SERVERPOD_DATABASE_PORT: "5432" # Port PostgreSQL
  SERVERPOD_SESSION_CONSOLE_LOG_ENABLED: "true"
  SERVERPOD_SESSION_CONSOLE_LOG_FORMAT: "text"
  SERVERPOD_APPLY_MIGRATIONS: "true"
  SERVERPOD_DATABASE_REQUIRE_SSL: "false" # 📝 Mettre à true si vous activez le TLS interne (voir étape 7)
