apiVersion: batch/v1
kind: Job
metadata:
  name: beu-cro-adv-daba-26
  namespace: beu-cro-adv-daba-26
spec:
  activeDeadlineSeconds: 86400  # 24 h
  backoffLimit: 3
  template:
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
        - name: beu-cro-adv-daba-26
          image: registry.forge.hefr.ch/lena.beust/adv-daba-26:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: beu-cro-adv-daba-26-config
          resources:
            requests:
              memory: "3000Mi"
              cpu: "2000m"
            limits:
              memory: "3000Mi"
              cpu: "2000m"
      restartPolicy: Never
