apiVersion: v1
kind: Secret
metadata:
  name: beu-cro-adv-daba-26-secrets
  namespace: beu-cro-adv-daba-26 # 📝 Remplacer par votre namespace
type: Opaque
stringData:
  postgres-user: "neo4j"  # 📝 À changer !
  postgres-password: "test"     # 📝 À changer !
  postgres-db: "beu-cro-adv-daba-26"         # 📝 À changer !
