apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamer
  namespace: beu-cro-adv-daba-26
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamer
  template:
    metadata:
      labels:
        app: streamer
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret 
      containers:
        - name: streamer
          image: registry.forge.hefr.ch/lena.beust/adv-daba-26:latest
          env:
            - name: JSON_FILE
              value: "http://vmrum.isc.heia-fr.ch/files/DBLP-Citation-network-V18.jsonl"
            - name: MAX_NODES
              value: "10000"
            - name: BATCH_SIZE
              value: "5000"
            - name: NEO4J_IP
              value: "neo4j" 
          resources:
            limits:
              memory: "4Gi"
